apiVersion: v1
kind: Service
metadata:
  name: courseproj1-frontend-nodeport
  labels:
    app: courseproj1-frontend
spec:
  type: NodePort
  selector:
    app: courseproj1-frontend
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
    nodePort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: courseproj1-frontend
  labels:
    app: courseproj1-frontend
spec:
  selector:
    matchLabels:
      app: courseproj1-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: courseproj1-frontend
    spec:
      containers:
        - image: nqmaigre/courseproj1-frontend
          name: courseproj1-frontend
          ports:
            - containerPort: 5000
