apiVersion: v1
kind: Service
metadata:
  name: courseproj1-jupyter-nodeport
  labels:
    app: courseproj1-jupyter
spec:
  type: NodePort
  selector:
    app: courseproj1-jupyter
  ports:
  - name: http
    port: 8888
    targetPort: 8888
    protocol: TCP
    nodePort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: courseproj1-jupyter
  labels:
    app: courseproj1-jupyter
spec:
  selector:
    matchLabels:
      app: courseproj1-jupyter
  replicas: 1
  template:
    metadata:
      labels:
        app: courseproj1-jupyter
    spec:
      containers:
        - image: nqmaigre/courseproj1-jupyter
          name: courseproj1-jupyter
          ports:
            - containerPort: 8888
