apiVersion: v1
kind: Service
metadata:
  name: courseproj1-jupyter
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 60003
  selector:
    app: courseproj1-jupyter
